PrecacheHUDMaterial( "HUD/capture_point_status_orange_a" )
PrecacheHUDMaterial( "HUD/capture_point_status_orange_b" )
PrecacheHUDMaterial( "HUD/capture_point_status_orange_c" )
PrecacheHUDMaterial( "HUD/capture_point_status_blue_a" )
PrecacheHUDMaterial( "HUD/capture_point_status_blue_b" )
PrecacheHUDMaterial( "HUD/capture_point_status_blue_c" )
PrecacheHUDMaterial( "HUD/capture_point_status_grey_a" )
PrecacheHUDMaterial( "HUD/capture_point_status_grey_b" )
PrecacheHUDMaterial( "HUD/capture_point_status_grey_c" )

PrecacheHUDMaterial( "HUD/capture_point_status_round_orange_a" )
PrecacheHUDMaterial( "HUD/capture_point_status_round_orange_b" )
PrecacheHUDMaterial( "HUD/capture_point_status_round_orange_c" )
PrecacheHUDMaterial( "HUD/capture_point_status_round_blue_a" )
PrecacheHUDMaterial( "HUD/capture_point_status_round_blue_b" )
PrecacheHUDMaterial( "HUD/capture_point_status_round_blue_c" )
PrecacheHUDMaterial( "HUD/capture_point_status_round_grey_a" )
PrecacheHUDMaterial( "HUD/capture_point_status_round_grey_b" )
PrecacheHUDMaterial( "HUD/capture_point_status_round_grey_c" )

VPKNotifyFile( "materials/correction/mp_ability_sonar_forever.raw" )
VPKNotifyFile( "materials/correction/mp_ability_sonar.raw" )
VPKNotifyFile( "materials/correction/overdrive1.raw" )
VPKNotifyFile( DMR_SONAR_SCOPE_COLOR_CORRECTION )
VPKNotifyFile( ELECTRIC_SMOKESCREEN_DAMAGE_COLORCORRECTION )

VPKNotifyFile( "cfg/startup.cfg" )
VPKNotifyFile( "cfg/startup_retail.cfg" )

PrecacheHUDMaterial( "../loadscreens/mp_airbase_widescreen" )
PrecacheHUDMaterial( "../loadscreens/mp_angel_city_widescreen" )
PrecacheHUDMaterial( "../loadscreens/mp_boneyard_widescreen" )
PrecacheHUDMaterial( "../loadscreens/mp_colony_widescreen" )
PrecacheHUDMaterial( "../loadscreens/mp_corporate_widescreen" )
PrecacheHUDMaterial( "../loadscreens/mp_fracture_widescreen" )
PrecacheHUDMaterial( "../loadscreens/mp_lagoon_widescreen" )
PrecacheHUDMaterial( "../loadscreens/mp_nexus_widescreen" )
PrecacheHUDMaterial( "../loadscreens/mp_o2_widescreen" )
PrecacheHUDMaterial( "../loadscreens/mp_outpost_207_widescreen" )
PrecacheHUDMaterial( "../loadscreens/mp_overlook_widescreen" )
PrecacheHUDMaterial( "../loadscreens/mp_relic_widescreen" )
PrecacheHUDMaterial( "../loadscreens/mp_rise_widescreen" )
PrecacheHUDMaterial( "../loadscreens/mp_smugglers_cove_widescreen" )
PrecacheHUDMaterial( "../loadscreens/mp_training_ground_widescreen" )
PrecacheHUDMaterial( "../loadscreens/mp_runoff_widescreen" )

PrecacheHUDMaterial( "../loadscreens/mp_runoff_widescreen" )
PrecacheHUDMaterial( "../loadscreens/mp_swampland_widescreen" )
PrecacheHUDMaterial( "../loadscreens/mp_wargames_widescreen" )

//PlayerStatusCounts
PrecacheHUDMaterial( "../ui/icon_status_pilot_enemy" )
PrecacheHUDMaterial( "../ui/icon_status_titan_enemy" )
PrecacheHUDMaterial( "../ui/icon_status_burncard_enemy" )
PrecacheHUDMaterial( "../ui/icon_status_pilot_friendly" )
PrecacheHUDMaterial( "../ui/icon_status_titan_friendly" )
PrecacheHUDMaterial( "../ui/icon_status_titan_neutral" )
PrecacheHUDMaterial( "../ui/icon_status_burncard_friendly" )
PrecacheHUDMaterial( "HUD/hud_hex_8v8_bg_left" )


//MFD stuff. Long term need a better way to gamemode specific precaches
PrecacheParticleSystem( "P_RNK" )
PrecacheParticleSystem( "P_MFD" )
PrecacheParticleSystem( "P_MFD_unmark" )
PrecacheHUDMaterial( "HUD/mfd_pre_friendly" )
PrecacheHUDMaterial( "HUD/mfd_friendly" )
PrecacheHUDMaterial( "HUD/mfd_enemy" )

// Coop Precaches
PrecacheHUDMaterial( "HUD/coop/coop_titan" )
PrecacheHUDMaterial( "HUD/coop/coop_nuke_titan_square" )
PrecacheHUDMaterial( "HUD/coop/coop_mortar_titan_square" )
PrecacheHUDMaterial( "HUD/coop/coop_emp_titan_square" )
PrecacheHUDMaterial( "HUD/coop/coop_char_frame_p1" )
PrecacheHUDMaterial( "HUD/coop/coop_char_frame_p2" )
PrecacheHUDMaterial( "HUD/coop/coop_char_frame_p3" )
PrecacheHUDMaterial( "HUD/coop/coop_char_frame_p4" )
PrecacheHUDMaterial( "HUD/coop/coop_char_brp_f" )
PrecacheHUDMaterial( "HUD/coop/coop_char_brp_m" )
PrecacheHUDMaterial( "HUD/coop/coop_char_cqp_f" )
PrecacheHUDMaterial( "HUD/coop/coop_char_cqp_m" )
PrecacheHUDMaterial( "HUD/coop/coop_char_dmp_f" )
PrecacheHUDMaterial( "HUD/coop/coop_char_dmp_m" )
PrecacheHUDMaterial( "HUD/coop/coop_char_atlas" )
PrecacheHUDMaterial( "HUD/coop/coop_char_ogre" )
PrecacheHUDMaterial( "HUD/coop/coop_char_stryder" )
PrecacheHUDMaterial( "HUD/coop/coop_char_spectre" )
PrecacheHUDMaterial( "HUD/coop/coop_ammo_locker_icon" )
PrecacheHUDMaterial( "../ui/td_wave_icon_mortartitan" )
PrecacheHUDMaterial( "../ui/td_wave_icon_emptitan" )
PrecacheHUDMaterial( "../ui/td_wave_icon_cloaked_drone" )
PrecacheHUDMaterial( "../ui/td_wave_icon_spectre" )
PrecacheHUDMaterial( "../ui/td_wave_icon_suicide" )
PrecacheHUDMaterial( "../ui/td_wave_icon_sniper" )
PrecacheHUDMaterial( "hud/coop/wave_callout_strip" )
PrecacheHUDMaterial( "hud/coop/wave_callout_strip_lines" )
PrecacheHUDMaterial( "hud/coop/wave_callout_hazard" )
PrecacheHUDMaterial( "hud/coop/hud_hex_line_bg_left" )
PrecacheHUDMaterial( "hud/coop/hud_hex_bg_left" )
PrecacheHUDMaterial( "hud/coop/hud_hex_left" )
PrecacheHUDMaterial( "hud/coop/hud_hex_line_left" )
PrecacheHUDMaterial( "hud/coop/hud_score_strip_coop" )
PrecacheHUDMaterial( "hud/coop/hud_score_strip_bg_coop" )
PrecacheHUDMaterial( "hud/coop/score_notification_flare" )
PrecacheHUDMaterial( "hud/coop/hud_hex_8v8_bg_left" )
PrecacheHUDMaterial( "hud/coop/icon_status_dead" )
PrecacheHUDMaterial( "hud/coop/mini_turret_counter" )
